from typing import BinaryIO, Protocol


class StorageBackend(Protocol):
    max_file_size: int

    def generate_key(self, filename: str) -> str: ...

    def save(self, file: BinaryIO, storage_key: str) -> int: ...

    def read(self, storage_key: str) -> BinaryIO: ...

    def delete(self, storage_key: str) -> None: ...

    def exists(self, storage_key: str) -> bool: ...
